# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of R's sample function with probabilities
#' @param x NumericVector - The input vector from R
#' @param size int - The number of elements to sample
#' @param replace bool - Whether sampling is done with replacement
#' @param prob NumericVector - The probabilities of elements to sample
#' @return NumericVector - The sampled elements
#' @export
sample_cpp_prob <- function(x, size, replace = FALSE, prob = numericVector()) {
    .Call('_SA23204186_sample_cpp_prob', PACKAGE = 'SA23204186', x, size, replace, prob)
}

